[package]
name = "people_polls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
edgedb-tokio = "0.3.0"
anyhow = "1.0.66"
tokio = { version = "1.21.2", features = ["full"] }